language: node_js
cache:
  directories:
  - $HOME/.npm
notifications:
  email: false
node_js: 10
before_install:
- npm install -g npm
before_script:
- npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-update
after_script:
- npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-upload
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
